services:
  postgres:
    image: postgres:latest
    container_name: learning_go_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./migration:/docker-entrypoint-initdb.d